package model;
// Generated 12/01/2017 03:29:53 by Hibernate Tools 4.3.1

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Palestra generated by hbm2java
 */
@Entity
@Table(name = "palestra",
         catalog = "lp4"
)
public class Palestra implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    private Integer id;

    @JoinColumn(name = "id_palestrante")
    @ManyToOne
    private Palestrante idpalestrante;

    @Column(name = "assunto")
    private String assunto;

    public Palestra() {
    }

    public Palestra(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Palestrante getIdpalestrante() {
        return idpalestrante;
    }

    public void setIdpalestrante(Palestrante idpalestrante) {
        this.idpalestrante = idpalestrante;
    }

    public String getAssunto() {
        return assunto;
    }

    public void setAssunto(String assunto) {
        this.assunto = assunto;
    }

    @Override
    public String toString() {
         return "model.Palestra[ id=" + id + " ]";
    }
    


}
